M48
; DRILL file {KiCad 7.0.1} date Wed Apr  3 13:53:11 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-03T13:53:11+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0469
%
G90
G05
T1
X5.3937Y-3.6378
X5.3937Y-3.4097
T2
X5.1339Y-2.8445
X5.1339Y-4.7776
T0
M30
